model:
  type: dinov2
  source: torch_hub
  repo: facebookresearch/dinov2
  name: dinov2_vits14
  embedding_dim: 384

inference:
  top_k: 10
  dist_epsilon: 100
  score_epsilon: 0.72
  beta: 10
  anchor_bonus_weight: .5